---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: doe25-group-13
spec:
  encryptedData:
    .dockerconfigjson: AgAX0QPAacDF6Y0q/Gxk26kcsLRn02C5o0r/wKkC5XP1y5uktBawlzdQK2ubQSCmKlDBkHbM66xFQUZqrAmCjhpSeUlcyqhLaEZxxlwmJW1jFexUJXpaCrU3QwYtbNQWxvnmfvm+MJwnDWcw7TQvHkTBESAyahoUrRaHSDzeenZ62D5u9UqHHfKQODBgJEfckLx8/ZUWy6QDISgqvxsgfAnCz38KZ+tLIoXs/7mVe2rEzRJZH5kpfsPqdFjakhOFEU/drA92rKX+rPNeIKe8XQ9MJWe2MzDy68M+isMeCbtZUYrgmn3FC83CIuVn7PYSV8GBei/sqOqavel7rbzGYLymWo1GZxzrzzk2GGF1XIs2kX0mIzF2+22oMbdsaeF4fH3pn8qKvKwQRjJdQ4FgSbga6jEVwneJJKFdu1GyUrivCnGaMhK2BiHnlZOVXVfSRXcO0YwivzjWdEcqpHVTPle6cfZIkiUhayzL2zvtnYPaThQOaTwXR5Cjsspa/YcwCmxKS0sckXnz6R+9kFCUrlFD66RPRxp+RNvVAeNyIoh2Nt+QRlhhQOVxC1NIMKxgnrCArIl/gQ1xGxDAuVSZKGDZquBaSlSyYdcQIb7a5IJP/79P8B+sXu4WHJjUsv6fPX7X2PcFjhvnhcchW2SNJXwHa/Z5GaOr3OzpvBdjgCt5jInRqI34NJBz8Dhy2shfyuBrPPkHmhIZ6d+fWIMrZesUFUr/xEBF+Q1Imkh7bOn3gpDzK9aBvgrzgaetScKL1/F/lU1H+A8YGYhp1mxhDbVlUfxJr37NXLahmxTobUjdOME7iXGeorsRzGaQn61NjSmOLoPxn1AmyJpdqnP1PIPnTuGLYFUj6MVsag8zekQWOpOZeRo7znRVZLuZJcD6c149gGvudyMpsx9Svlcw+LM5STLothLtxvVH7nfNHaeu0mz7GLok3YrpXA8QlQgjj34D7D1i5NXTaZFejOKX0Bn1HccCtG72BYciuXhwNMiJ1cj2j8SfiCkWVuM=
  template:
    metadata:
      name: registry-credentials
      namespace: doe25-group-13
    type: kubernetes.io/dockerconfigjson
