---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-key
  namespace: doe25-group-13
spec:
  encryptedData:
    Jwt__SigningKey: AgCUmMd7NYfiINMHO3r4P+c9t6xQk/m2ZTgLsI/7pKyee5P7MYJTqVxXE2rYbGEnAQsxW7c5HRbw3xOz3WxNZiNMJ8AzVXTbEN03HQdUms73VvS2sm+1twbdUgfDdSwA6xxHBh4JX5UQBpQum4ZVuIemU5eZFik8u1il19nyD8Btmp9Pfcpttarg0hd+tbl1bbLaxeZJYgEAY/FBbbrFkJ5T/Fy9NM5cOecuP5j80kOOzqpC+KTuI0umxNgwQLIe2AIYwxNXpQf/epOsVIgnNgTGSKk/FaJAyRskE6MvD2PYvSdQnshB8xp8hH5+U+22QNdzLVgxkMthKLSetao6u3SVqlsdVZHGBXjmXQtUsnBgBS/fkMUNWQEy1iFv+O9MnV2k9WQ7xyKvNDSRLapymk20Jwyjc7vMljLM1Bi9lqQtswSDiQY6cmmUNvWrLSQSCq4CDKxWptKxGT4jY54fsMDquWzGwG6yDu0q6VDvu7qNf9ZsLs98SpCPWyG+UaAA7u0+kfxDLZpmle00ljHM64uIkfkqjtRH2fP5NHyFYuJ6wODjuX5Em0ESwlMYuMXQWAAGez+fss6vELFH1KscxO0pvpaERrdnQT40L92Nz97ULFwCUW31yRvB8d+aifDfz/gwjOFlQcv72L45iqnVSbUrRGRO2xWSsqCdMq2gxD0wh+OylAwLvaXxux6trCGmBNbs+WPMybMADsIc3LDuQIX9qXw8ESGwL9uwe20UR7ntYXlsUZfEvtkXUdIeBVnAFKhx/AKrLEgzq8ErcdIx0sX4
  template:
    metadata:
      name: jwt-key
      namespace: doe25-group-13
