---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mssql-secret
  namespace: doe25-group-13
spec:
  encryptedData:
    MSSQL_SA_PASSWORD: AgAp19BGWTHf7/M9WmFqVRsWWbdTObmwpssB650dlM17PpXf12C2CAu0AiS7KlREHCjfGWOKPeznakzeqn/ILefmmWJDqQh3qVIn0R6tsyelna4IAgqQq28smgf2FKaoHCOYVQGsC9cJAa/jNOB5TkvcAIDw4RyEDtw/h/J0u0bvgLZKlwa1oAA/SQmj8dVZX7PHc0yXDxLoAitKwK2w/GlLfx1c3LsBFA7rR6w1MZuQ665z27mGYIVTwxU0PpJwQUI7a+CPiDvqsp9Mo9tPEXtXqMFHVhzvPHN03/27f1wSW5CeqUFeLSPFvs5K3b8F8vqnledd/qDn9UjrXw4DXo/hbVYDGAKCpFSLRFqHPkRTUGINNDEB3KWGxy9Aqyr1AV+BNKWOT/jrIFfayw4H4yH5E/Tf/tdSVxkoHHArYCoZ4DCG7ChfR97pPLebx8ZT64u8snGEN2J7k3CW60bzYvHY7cun2mLafYGJ5luaiAQMc+5JE9p593SKWfWsafNJc7e/MBHCkltMYh9dpEQNunjZPp8HfI/EUWPr8v9zA2XZUsJuM5Z9oX9sjyGmZ1ir1/3ojoMQVojlHwvGE3f9Du2Q2IaN6ma/WpUvsduAhABHJEPOoXLsyBoT0nIwYqsRu+jp4rg6m1Wnjn0g4Pk0CcbLedRz5dcKMyiSgg3vbXbc0mMBKl92GThq0n8SD5AYN4qpEOhHkPNmriuvB8O0d53rvNFu6TKl6wiz
  template:
    metadata:
      name: mssql-secret
      namespace: doe25-group-13
