---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adminer-basic-auth
  namespace: doe25-group-13
spec:
  encryptedData:
    users: AgB+sOxAJRUZ2RJS/pxQlvDkcF5G6H1XRgxWivYVW9P7R/3odMF6WCpFnpIgQbnF4Qo6USSOYco2OJIxakaWomNWKPnPq5xdtcSn2OUmRWQPqJmDK/jdSgvo0+gclep+adE11nlE5XFvFXNQ0sQbn6c047ekhhajFcZOeQXCwaS7yK2D30KfRIUNuVfS/Pj7UqGhC/xJT9khn4CkQ0N3zpNMpNczyVAiOYYpCQecJTNwoD+fluFgtLVEYTVFvwDoRpg+cNhFNR/kQGq3nH+EekuhjbuglJgolbYKx2tVjIURHIQbpBOrAAVRScW9NL+pxKLb8ekLzhzouoU1gMnGfOvn7Jky7WAEVAXA8GfuCGntlCxJA3Q0HJ+xhP8MkhdQbkB/ZwZu5IuUUZGjzJ9ObFEc2QgqAt6YglUsK7WBBWhZhYfaqMQ/RgFzwKGw4f0ptPqk1os0u75knnmpTRqaD/au1/6ANEU/BsHFGrAZ8XG4OdgC8uU+qZv+ulAKZnSp+CqBGWHXl4aLqheVTqDq2xrjJ2XWwPryTTVxJARYY11PrddJt3aeeP6Ei+uEcrjOvxqqZq+dFDtdKvvHvx/bWfzCH+LuRMuNnPCj8t6Wk/L6Jc0wXq72eN/ShEx/olbnG/HdZo0CGbah3sn7Jr9gPndBpS0wb5oaQtkGcRVqDpgjvdwyRFsBGp3unWc+iBBsqe4tpoRTB0upo+y3d4yarTFadyrhaVWhg5gQ8UQ8JthEOmP41cP25HUtwnavXAMsEVL7mYrhm+iMe+TU4R2RZPcRyPQ56Uw=
  template:
    metadata:
      name: adminer-basic-auth
      namespace: doe25-group-13
