apiVersion: v1
kind: Service
metadata:
  name: volunti-backend
  labels:
    app: volunti-backend
spec:
  type: ClusterIP
  selector:
    app: volunti-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
