workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:

  - build
  - test-build
  - container-build
  - test-container
  - security
  - deploy
  - cleanup

default:
  tags:
    - lab-vm # runner på VM från skolan

include:

  - local: 'backend/build.yml'
  - local: 'backend/test.yml'
  - local: 'backend/container-build.yml'
  - local: 'backend/deploy.yml'
  - local: 'frontend/build.yml'
  - local: 'frontend/test.yml'
  - local: 'frontend/container-build.yml'
  - local: 'monitoring/monitor-ci.yml'
  - local: 'frontend/deploy.yml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

sast:
  stage: security

secret_detection:
  stage: security
