apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: doe25-group-13-dev
namePrefix: burgundy-dev-
resources:
  - ../../base
  - secrets/sealed-secret-mssql.yaml
  - secrets/sealed-secret-jwt.yaml
  - secrets/sealed-secret-registry.yaml
  - secrets/sealed-secret-adminer-auth.yaml

images:
  - name: registry.chas-lab.dev/chas-challenge-2026/grupp-13/burgundy/backend
    newTag: latest
  - name: registry.chas-lab.dev/chas-challenge-2026/grupp-13/burgundy/frontend
    newTag: latest

patches:
  - path: patches/ingress.yaml
  - path: patches/backend.yaml

