---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adminer-basic-auth
  namespace: doe25-group-13-dev
spec:
  encryptedData:
    users: AgCIDZOt5HdM4q+TCszM8kjC+voSh3CrNgi3VhErTLT7jsIFOeZOPWTs+Pf2YPMERbkliWtGPh4bNV6C1nF4zXHVJcTnY+xVT2PRZOm+p8PsjdYdJ1vT787gOev7uu5axf6c3irOn3gNvitiG3M2R7bolpXeRXHvJH4SqZ+A1DNE1g295hlL+iBp6w/AWusR22mGNHCL8agTnZkg3CUbFnFfXE8v7Ys4IuRaWdFGE8iL8tXBEINTlGlN/r0wsCsFW+/vDxRdCDrk9tjr1IwqXOFDV/Ae5SmciXXeWtFECNrtZI+QopYFI0oOHETLxFPzRe/PvPKkBgcZ5zYxyYs0wIDp0JPWx9IMTEEQL4BX/dkyxp6m9JqbcOgyo2T27Fa7U3GB/7JiJQakWDkzFr8YDy05JzsYP/I9XRI4DmXK/lt+8j1eFayLjf4oRPN/hamvqEx0FYKXCYwHtBwsFjO3dNnFWU+NE0CycxbwNEew31jCE64hPv7gfzpsLTb71TTm2F+i9O6uUVexb8a+2a6c2bGLm5/OqkZnPYUJ9H5fbuPZOmIC8Jlm0OoII2FtOzFZFce5qNi8Wl0ENbj2vglZe362IAKHxpuVy7Alw+lBhEykBMIFpsMws/oMjH3uuADOfvGPkFy4zRe2CBnbj2dDDyfCbJaUs8k52DVdr32+ylbbvOgsjtH1BgVev5LGvsnRUZp1Ug8OxFrhRpjELfoWNHZ0FWdiJyRPDz41ibaa0qwlfhnnPzgxDK16C5IyRW2xOsQ4lD6eiYQaYv6sztkLOZ4Pg26lu8g=
  template:
    metadata:
      name: adminer-basic-auth
      namespace: doe25-group-13-dev
