---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mssql-secret
  namespace: doe25-group-13-dev
spec:
  encryptedData:
    MSSQL_SA_PASSWORD: AgDRaRq8+YW4y5xmW54Hm993Uu+qAqTtewWkEOeJYwRdvdT5QiKGiAcHFjC7u7fIVZ9vFippQrrqcukQPgE66VF7H86LFxsVEfFOtYPkYB84GoKQMbmDucFu1SgK3Y045KUHabf6EEilTYKf+4r618KIyepGihk+TrbwE3PsoXzsYvEKq7I+hw0UpIVlmJq1i9ddkyNAfE4TZa2+dRcs+1eD5/3HlkvlSejCH7ndBsB5e9tLlt7e8hsexbvopJonM8VwoQtJfdWFseVMyFHazU68ST062QiRbrCgS9y4W789T8EEV3cXo8529TJ87yVZ5Z2bb48WR8GuJNVZWTMVJQX268q0HXGn0nMtIvoMdhFKaUf4yYWPR23K18lpBUvrX01HFQC1nVJHIvrspTPON+rHl8lRAxKyrv0QbD16FfLXfKNEpG9WaTl/vhMpjTaw+cHaq0K1UtvC5+5IRh7CN8iWDVCO8IDC85FhGNvqEIErxG2Tbl/u4UmV+8rExCGfV6G6IjU52KlkszUwEddA9m8cWxrtBkLSecwkoXJ7iMAgURpuLNZd1fpFOEz+jYq3HMrKtufvWPfqIOWN6LeROujPdUKP8buTIocy9PJsRighJagbtqCBSlyM7W0r8rSjMg4mBaJtIyNl0c5bWvUVWxJmZB3f63fLCmj3nfxLICFQzyRN8VFUdW/kbQmsp3a3cTi04Sb0BEftKwSOSRK50wJo2wmrYxluWqUs
  template:
    metadata:
      name: mssql-secret
      namespace: doe25-group-13-dev
    type: Opaque
