---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: doe25-group-13-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBMUjN/8QKbrVD0MIpARDAPXhJpD5cp4p2D1vyS+7j2Utn7cpprqWAFJHkUfMBVWy3NVukLzpWyD7KN5MH0hE0EbkXJ+YEdts1wXO8Hag6h87kItCimmHJeOUbbK5/RXbvzQQKuhZUhrepW4AtJzX68yvaQBPV7l0JDYhLd8VxvQH5NLPUhuDVAYJE4aANxKQD1qoxfRDgYsP2sXIATiC2NBga+QfBG7sZtwluEibKq81NMo1mcA8vLq9d6zbJX82BQ9IfHjtfnqNOzhaY2MbrHAyfHrkD/sR2CyWZYey9sFO4ofaSgpze2G05JhIv5vuIEZ7NVAKkjOVUW8F05PCR0zpAtRTQG+Y4DzkYjv3ZV05HBPBcDz/y7iM4oYdel5XpBiTS+PO5A/rlNshxcFNFCNPzCxsStMcGxBnGOdB1QIpvp5XY4W91avFS1NpcFC8yMkHTA+I3dALANptAy31Rp+XoQdi/E0zL4Z2m3kH6GMK7AazgchplM4TvV8LxMPK9Gqzo8F9tUBZ+7Egg3+ElTSwwo5EvrXuM5+oKNlbSAGnkpfOlD7+LzpJEG3QiJHr+2tV7LZb4iWwT+q98H8yZ+43RlunlLIBnv3CU6YykJE7lkfURpD5UOzDeiNdT/XsSLP29YgJn+jFdF/tNmVyNn+aQAjrNF6XJiO3z1acO77AYNika48TSFYmNxoJAKCLHM6cN2sNcpasbUTNrYlBPJfVfpM9oZBnU6/NQsIWCtXlPDC6UdSzCd0a2M9XD6pPriqlr/IX0mw/QDYpkx2B1mQpvZJPgaqyXai8zrxSpvxvbmfrq1ToggL2BLpjmeKkP5IQgkNphrdN5IWHzER77FLtCgG5bhvfe4vKe1ctN4riBgp026UcNrUaqjr8aoIFqlqYZRK3Ths57T0nYUvTKSeTPjX6t9MAUH7EWcCexY6UzTFTOrTa+AzToo0H58AwcDcWELxN00K9vCdNmBhVC6WraqvOOaU1NRMx9VJA7yNVkkH+TiLwUz8DU=
  template:
    metadata:
      name: registry-credentials
      namespace: doe25-group-13-dev
    type: kubernetes.io/dockerconfigjson
