---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-key
  namespace: doe25-group-13-dev
spec:
  encryptedData:
    Jwt__SigningKey: AgCBLTFt5U/CPK+xxbIP2pcc78K+naXQV56CZNWIwPSiIsUGhEiOGMCILQUlmMDZY3fY1rC09MdblmRiEeay/VIeI3VfbzPArUeuVfjpSxJ+A7VIpXGHtFMQP9BOm39i5HKkZ2I9vPcrV7Xb8oyMMSc/YrxWFhsEz7z7AFUAV+2FAYPlR2J12vfnQ+lmauSJGKtmsn1qDcOny2H3Ipa094WLjIjFhj/qT9NrTKqwfAKqSDRCXVl+rYVd82yzJZyYIiORrjNrorf5ytWF5rg9l195f0c0XxEGC2hmVJ/akc3/ziXb5xzWEcvbbY0JsOWTz5uXDbLJOaQSN+gOyj9E+v77FTrnh5u9LFtZ0NeHLvvkICh+QQBv776D63wQ2rzk6+AMl/PNdsQEdXLMTKSq/i5GOTXEAhU2FCkmFFb+j/TmwiFx7Tc7taORJa4IRkGqZbfUUNEWmX8XvG2uoyigzWqdzCq+DSOxblhHzJ7imytzWZKxy8yZIbc1ObcwyAqMmN5Vnt9xq9KNlc92p6/bwr+jiMl4DFL5Z5/LzDVNvlXj0BZrFW9TFxqDqoi1RZNc6VhakgPPa1kVldAAvFbw9zCf4TiWbJ6F1YPzX9OFHuPqkj77o5bsa39bkI6jkLH5O0h+EB44KSgh74wDztNgIUPuP0s4uQ0izYyV93Ez1QdAIDTGvZ09Ab6O0vIt5+KcQOB4tfjFCyDLaq3cjFXYpyxzS87+AohUbdGr5Q8NE13FNuWmbUloTkwAtzz3oFmkLLjg39eUtqjG4j2o0BQJpyAf
  template:
    metadata:
      name: jwt-key
      namespace: doe25-group-13-dev
    type: Opaque
